(function(){"use strict";
function $(id){return document.getElementById(id)}function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
var M=$("messages"),P=$("prompt"),S=$("sendBtn"),A=$("attachBtn"),picker=$("imagePicker"),AP=$("attachPreview"),usageLine=$("usageLine");
var drawerO=$("drawerOverlay"),drawer=$("drawer"),chatList=$("chatList"),search=$("chatSearch"),settingsO=$("settingsOverlay"),settingsSheet=$("settingsSheet"),modelO=$("modelOverlay"),modelSheet=$("modelSheet"),menuO=$("msgMenuOverlay"),msgMenu=$("msgMenu");
var keyInput=$("apiKey"),modelSelect=$("modelSelect"),instructionsInput=$("instructions"),usageToggle=$("usageToggle"),modelLabel=$("modelLabel");
var mem={},chats=[],projects=[],active=null,activeProject=null,actionChatId=null,running=false,aborter=null,pendingImage=null,menuText="",lastUsage=null,normalH=window.innerHeight;
function get(k,d){try{var v=localStorage.getItem(k);return v===null?d:v}catch(e){return Object.prototype.hasOwnProperty.call(mem,k)?mem[k]:d}}function set(k,v){mem[k]=v;try{localStorage.setItem(k,v)}catch(e){}}function parse(k,d){try{var v=JSON.parse(get(k,""));return v||d}catch(e){return d}}
var key=get("oai_key",""),model=get("oai_model","gpt-5.6-luna"),instructions=get("oai_instructions",""),showUsage=get("oai_usage","0")==="1";chats=parse("cg15_chats",[]);projects=parse("cg15_projects",[]);
keyInput.value=key;modelSelect.value=model;instructionsInput.value=instructions;usageToggle.checked=showUsage;modelLabel.textContent=modelName(model);
function modelName(x){return x==="gpt-5.6-sol"?"GPT-5.6 Sol":x==="gpt-5.6-terra"?"GPT-5.6 Terra":"GPT-5.6 Luna"}function show(x){x.classList.remove("hidden")}function hide(x){x.classList.add("hidden")}function saveChats(){set("cg15_chats",JSON.stringify(chats))}function saveProjects(){set("cg15_projects",JSON.stringify(projects))}function current(){for(var i=0;i<chats.length;i++)if(chats[i].id===active)return chats[i];return null}
function createChat(){var c={id:"c"+Date.now(),title:"New chat",projectId:activeProject,created:Date.now(),updated:Date.now(),messages:[]};chats.unshift(c);active=c.id;saveChats();return c}function titleFor(t){t=(t||"Image chat").replace(/\s+/g," ").trim();return t.length>38?t.slice(0,38)+"…":t}
function escapeHTML(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}function md(text){var s=escapeHTML(text),blocks=[];s=s.replace(/```([\s\S]*?)```/g,function(_,x){blocks.push("<pre><code>"+x+"</code></pre>");return "@@B"+(blocks.length-1)+"@@"});s=s.replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2">$1</a>');var ps=s.split(/\n{2,}/).map(function(x){return x.indexOf("<pre>")===0||/^<h[123]>/.test(x)?x:"<p>"+x.replace(/\n/g,"<br>")+"</p>"}).join("");blocks.forEach(function(b,i){ps=ps.replace("@@B"+i+"@@",b)});return ps}
function bubble(role,text,img,thinking){var row=document.createElement("div");row.className="message "+role;var w=document.createElement("div");w.className="bubbleWrap";var b=document.createElement("div");b.className="bubble";if(img){var im=document.createElement("img");im.className="messageImg";im.src=img;b.appendChild(im)}var t=document.createElement("div");t.className="bubbleText";t.innerHTML=thinking?'<div class="thinking"><i></i><i></i><i></i></div>':md(text);b.appendChild(t);w.appendChild(b);if(role==="assistant"&&!thinking){var tools=document.createElement("div");tools.className="msgTools";var copy=document.createElement("button");copy.textContent="Copy";copy.onclick=function(){copyText(text)};var more=document.createElement("button");more.textContent="•••";more.onclick=function(){menuText=text;show(menuO)};tools.appendChild(copy);tools.appendChild(more);w.appendChild(tools)}row.appendChild(w);M.appendChild(row);return{row:row,text:t}}
function render(){M.innerHTML="";var c=current();if(!c||!c.messages.length){M.innerHTML='<section class="welcome"><div class="orb">✦</div><h1>What can I help with?</h1><p>ChatGPT for iOS 15</p></section>';return}c.messages.forEach(function(m){bubble(m.role,m.text,m.image,false)});bottom()}
function renderChats(){var q=(search.value||"").toLowerCase();chatList.innerHTML="";chats.filter(function(c){return !q||c.title.toLowerCase().indexOf(q)>=0}).forEach(function(c){var r=document.createElement("div");r.className="chatRow";var o=document.createElement("button");o.className="chatOpen";o.innerHTML='<span class="chatTitle">'+escapeHTML(c.title)+'</span><span class="chatDate">'+new Date(c.updated).toLocaleString()+'</span>';o.onclick=function(){active=c.id;render();hide(drawerO)};var more=document.createElement("button");more.className="chatMore";more.textContent="•••";more.onclick=function(e){e.stopPropagation();openChatActions(c.id)};r.appendChild(o);r.appendChild(more);chatList.appendChild(r)});if(!chatList.children.length)chatList.innerHTML='<p class="note">No chats yet.</p>'}
function renderProjects(){renderInlineProjects();var list=$("projectList"),activeBox=$("projectActive");list.innerHTML="";var ap=projectById(activeProject);if(ap){activeBox.classList.remove("hidden");activeBox.innerHTML="<b>"+escapeHTML(ap.name)+"</b><span>New chats will be added to this project.</span>"}else{activeBox.classList.add("hidden");activeBox.innerHTML=""}projects.forEach(function(p){var count=chats.filter(function(c){return c.projectId===p.id}).length;var row=document.createElement("div");row.className="projectRow";var open=document.createElement("button");open.className="projectOpen";open.innerHTML="<b>"+escapeHTML(p.name)+"</b><span>"+count+" chats</span>";open.onclick=function(){openProjectEditor(p.id)};var del=document.createElement("button");del.className="projectDelete";del.textContent="×";del.onclick=function(){if(confirm("Delete project? Chats will be kept.")){chats.forEach(function(c){if(c.projectId===p.id)c.projectId=null});projects=projects.filter(function(x){return x.id!==p.id});if(activeProject===p.id)activeProject=null;saveChats();saveProjects();renderProjects()}};row.appendChild(open);row.appendChild(del);list.appendChild(row)});if(!projects.length)list.innerHTML='<p class="note">Create a project to group related chats.</p>'}
function actionChat(){return chats.find(function(c){return c.id===actionChatId})||null}
function openChatActions(id){actionChatId=id;var c=actionChat();if(!c)return;$("chatActionTitle").textContent=c.title;$("chatProjectChoices").classList.add("hidden");show($("chatActionOverlay"))}
$("chatActionCancel").onclick=function(){hide($("chatActionOverlay"))};$("chatActionOverlay").onclick=function(e){if(e.target===$("chatActionOverlay"))hide($("chatActionOverlay"))};$("chatActionSheet").onclick=function(e){e.stopPropagation()};
$("chatRenameBtn").onclick=function(){var c=actionChat();if(!c)return;var n=prompt("Rename chat",c.title);if(n!==null&&n.trim()){c.title=n.trim();c.updated=Date.now();saveChats();renderChats();$("chatActionTitle").textContent=c.title}hide($("chatActionOverlay"))};
$("chatDeleteBtn").onclick=function(){var c=actionChat();if(!c)return;if(confirm("Delete \""+c.title+"\"?")){chats=chats.filter(function(x){return x.id!==c.id});if(active===c.id)active=null;saveChats();renderChats();render();hide($("chatActionOverlay"))}};
$("chatProjectBtn").onclick=function(){var c=actionChat(),box=$("chatProjectChoices");if(!c)return;box.innerHTML="";var none=document.createElement("button");none.className="chatProjectChoice"+(!c.projectId?" current":"");none.textContent="No project";none.onclick=function(){c.projectId=null;c.updated=Date.now();saveChats();renderChats();renderInlineProjects();hide($("chatActionOverlay"))};box.appendChild(none);projects.forEach(function(p){var b=document.createElement("button");b.className="chatProjectChoice"+(c.projectId===p.id?" current":"");b.textContent=p.name;b.onclick=function(){c.projectId=p.id;c.updated=Date.now();saveChats();renderChats();renderInlineProjects();hide($("chatActionOverlay"))};box.appendChild(b)});if(!projects.length){var empty=document.createElement("div");empty.className="chatProjectEmpty";empty.textContent="No projects yet.";box.appendChild(empty)}box.classList.toggle("hidden")};
function renderInlineProjects(){var box=$("inlineProjects");box.innerHTML="";projects.forEach(function(p){var wrap=document.createElement("div");wrap.className="inlineProjectGroup";var row=document.createElement("div");row.className="inlineProjectRow";var op=document.createElement("button");op.className="inlineProjectOpen";op.innerHTML='<span class="projectRowName">'+escapeHTML(p.name)+'</span><span class="projectRowChevron"></span>';var children=document.createElement("div");children.className="projectChildren hidden";op.onclick=function(){var opening=children.classList.contains("hidden");children.classList.toggle("hidden",!opening);op.classList.toggle("expanded",opening);if(opening)renderProjectChildren(p,children)};var more=document.createElement("button");more.className="inlineProjectMore";more.textContent="•••";more.onclick=function(e){e.stopPropagation();openProjectEditor(p.id)};row.appendChild(op);row.appendChild(more);wrap.appendChild(row);wrap.appendChild(children);box.appendChild(wrap)});var add=document.createElement("button");add.className="inlineNewProject";add.textContent="＋ New project";add.onclick=function(){var n=prompt("Project name","");if(n&&n.trim()){var p={id:"p"+Date.now(),name:n.trim(),instructions:"",notes:"",created:Date.now(),updated:Date.now()};projects.unshift(p);saveProjects();renderInlineProjects();openProjectEditor(p.id)}};box.appendChild(add)}
function renderProjectChildren(p,box){box.innerHTML="";var pcs=chats.filter(function(c){return c.projectId===p.id}).sort(function(a,b){return b.updated-a.updated});var add=document.createElement("button");add.className="projectChildNew";add.textContent="＋ New chat";add.onclick=function(e){e.stopPropagation();activeProject=p.id;active=null;hide(drawerO);render();P.focus()};box.appendChild(add);pcs.forEach(function(c){var row=document.createElement("div");row.className="projectChildRow";var open=document.createElement("button");open.className="projectChildOpen";open.textContent=c.title;open.onclick=function(e){e.stopPropagation();activeProject=p.id;active=c.id;hide(drawerO);render()};var more=document.createElement("button");more.className="projectChildMore";more.textContent="•••";more.onclick=function(e){e.stopPropagation();openChatActions(c.id)};row.appendChild(open);row.appendChild(more);box.appendChild(row)});if(!pcs.length){var empty=document.createElement("div");empty.className="projectChildEmpty";empty.textContent="No chats yet";box.appendChild(empty)}}
$("projectsBtn").onclick=function(){var box=$("inlineProjects"),open=box.classList.contains("hidden");box.classList.toggle("hidden",!open);this.classList.toggle("open",open);if(open)renderInlineProjects()};$("projectsClose").onclick=function(){hide($("projectsOverlay"))};$("projectsOverlay").onclick=function(e){if(e.target===$("projectsOverlay"))hide($("projectsOverlay"))};$("projectsSheet").onclick=function(e){e.stopPropagation()};$("createProject").onclick=function(){var n=$("projectName").value.trim();if(!n)return;projects.unshift({id:"p"+Date.now(),name:n,instructions:"",notes:"",created:Date.now(),updated:Date.now()});$("projectName").value="";saveProjects();renderProjects()};
function projectById(id){return projects.find(function(p){return p.id===id})||null}
function openProjectEditor(id){var p=projectById(id);if(!p)return;activeProject=id;$("projectEditName").value=p.name||"";$("projectEditInstructions").value=p.instructions||"";$("projectEditNotes").value=p.notes||"";$("projectEditTitle").textContent=p.name||"Project";renderProjectChats(p);hide($("projectsOverlay"));show($("projectEditOverlay"))}
function renderProjectChats(p){var box=$("projectChats");var arr=chats.filter(function(c){return c.projectId===p.id});box.innerHTML="<h3>Chats in this project ("+arr.length+")</h3>";arr.forEach(function(c){var row=document.createElement("div");row.className="projectChatRow";var op=document.createElement("button");op.className="projectChatOpen";op.textContent=c.title;op.onclick=function(){activeProject=p.id;active=c.id;hide($("projectEditOverlay"));hide(drawerO);render()};var del=document.createElement("button");del.className="projectChatDelete";del.textContent="×";del.onclick=function(){if(confirm("Delete this chat?")){chats=chats.filter(function(x){return x.id!==c.id});if(active===c.id)active=null;saveChats();renderProjectChats(p)}};row.appendChild(op);row.appendChild(del);box.appendChild(row)})}
$("projectEditClose").onclick=function(){hide($("projectEditOverlay"))};$("projectEditOverlay").onclick=function(e){if(e.target===$("projectEditOverlay"))hide($("projectEditOverlay"))};$("projectEditSheet").onclick=function(e){e.stopPropagation()};
$("projectEditSave").onclick=function(){var p=projectById(activeProject);if(!p)return;var n=$("projectEditName").value.trim();if(n)p.name=n;p.instructions=$("projectEditInstructions").value.trim();p.notes=$("projectEditNotes").value.trim();p.updated=Date.now();saveProjects();$("projectEditTitle").textContent=p.name;renderProjects();render()};
$("projectNewChat").onclick=function(){if(!projectById(activeProject))return;active=null;hide($("projectEditOverlay"));hide(drawerO);render();P.focus()};
$("projectDelete").onclick=function(){var p=projectById(activeProject);if(!p)return;if(confirm("Delete project? Its chats will stay in Chat History.")){chats.forEach(function(c){if(c.projectId===p.id)c.projectId=null});projects=projects.filter(function(x){return x.id!==p.id});activeProject=null;saveChats();saveProjects();hide($("projectEditOverlay"));renderProjects();render()}};
function bottom(){requestAnimationFrame(function(){M.scrollTop=M.scrollHeight})}function resize(){P.style.height="auto";P.style.height=Math.min(P.scrollHeight,126)+"px";P.style.overflowY=P.scrollHeight>126?"auto":"hidden"}function sendState(){S.disabled=running||(!P.value.trim()&&!pendingImage);S.classList.toggle("stop",running)}
$("menuBtn").onclick=function(){renderChats();show(drawerO)};$("drawerClose").onclick=function(){hide(drawerO)};drawerO.onclick=function(e){if(e.target===drawerO)hide(drawerO)};drawer.onclick=function(e){e.stopPropagation()};$("newChatBtn").onclick=function(){active=null;activeProject=null;render();hide(drawerO);P.focus()};search.oninput=renderChats;
$("settingsBtn").onclick=function(){show(settingsO)};$("settingsClose").onclick=function(){hide(settingsO)};settingsO.onclick=function(e){if(e.target===settingsO)hide(settingsO)};settingsSheet.onclick=function(e){e.stopPropagation()};$("keyReveal").onclick=function(){var showKey=keyInput.type==="password";keyInput.type=showKey?"text":"password";this.textContent=showKey?"Hide":"Show"};
$("saveSettings").onclick=function(){if(!keyInput.value.trim()){alert("Enter your OpenAI API key.");return}key=keyInput.value.trim();model=modelSelect.value;instructions=instructionsInput.value.trim();showUsage=usageToggle.checked;set("oai_key",key);set("oai_model",model);set("oai_instructions",instructions);set("oai_usage",showUsage?"1":"0");modelLabel.textContent=modelName(model);hide(settingsO);renderUsage()};
$("modelBtn").onclick=function(){show(modelO)};modelO.onclick=function(e){if(e.target===modelO)hide(modelO)};modelSheet.onclick=function(e){e.stopPropagation()};qa(".modelChoice").forEach(function(b){b.onclick=function(){model=this.getAttribute("data-model");modelSelect.value=model;modelLabel.textContent=modelName(model);set("oai_model",model);hide(modelO)}});
A.onclick=function(){picker.click()};picker.onchange=function(){var f=this.files&&this.files[0];if(!f)return;if(f.size>7*1024*1024){alert("Please choose an image under 7 MB.");this.value="";return}var r=new FileReader();r.onload=function(){pendingImage=r.result;renderAttachment();sendState()};r.readAsDataURL(f)};function renderAttachment(){if(!pendingImage){AP.classList.add("hidden");AP.innerHTML="";return}AP.classList.remove("hidden");AP.innerHTML='<div class="attachCard"><img src="'+pendingImage+'"><span>Image attached</span><button id="rmImg">×</button></div>';$("rmImg").onclick=function(){pendingImage=null;picker.value="";renderAttachment();sendState()}}
P.oninput=function(){resize();sendState()};P.onkeydown=function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(!running)sendMessage()}};S.onclick=function(){if(running)stop();else sendMessage()};
function apiInput(c){return c.messages.map(function(m){if(m.role==="user"&&m.image)return{role:"user",content:[{type:"input_text",text:m.text||"What is in this image?"},{type:"input_image",image_url:m.image,detail:"auto"}]};return{role:m.role,content:m.text}})}function extract(d){var s="";(d.output||[]).forEach(function(i){(i.content||[]).forEach(function(x){if(x.type==="output_text")s+=x.text||""})});return s}
async function generateImage(promptText){if(!key){show(settingsO);return}hide(menuO);var c=current()||createChat();var wait=bubble("assistant","Generating image…",null,true);try{var res=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:"gpt-image-2.5-flare",prompt:promptText,size:"1024x1024"})});var data=await res.json();if(!res.ok)throw new Error(data&&data.error&&data.error.message?data.error.message:"Image generation failed");var item=data.data&&data.data[0];var src=item&&(item.b64_json?"data:image/png;base64,"+item.b64_json:item.url);if(!src)throw new Error("No image returned");wait.row.remove();c.messages.push({role:"assistant",text:"Generated image",image:src,generated:true});c.updated=Date.now();saveChats();render()}catch(e){wait.row.remove();c.messages.push({role:"assistant",text:"Image error: "+(e.message||String(e))});saveChats();render()}}
$("imageGenBtn").onclick=function(){var p=prompt("Describe the image to create",menuText);if(p&&p.trim())generateImage(p.trim())};
async function sendMessage(){var text=P.value.trim(),img=pendingImage;if(!text&&!img)return;if(!key){show(settingsO);return}var c=current()||createChat();if(!c.messages.length)c.title=titleFor(text);c.messages.push({role:"user",text:text,image:img||null});c.updated=Date.now();saveChats();P.value="";pendingImage=null;picker.value="";renderAttachment();resize();render();var wait=bubble("assistant","",null,true);running=true;aborter=new AbortController();sendState();bottom();
try{var body={model:model,input:apiInput(c),store:false,stream:true};var project=projectById(c.projectId);var combined=instructions;if(project){var projectContext="";if(project.instructions)projectContext+="Project instructions:\n"+project.instructions;if(project.notes)projectContext+=(projectContext?"\n\n":"")+"Project reference notes:\n"+project.notes;combined=combined?(combined+(projectContext?"\n\n"+projectContext:"")):projectContext}if(combined)body.instructions=combined;var res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify(body),signal:aborter.signal});if(!res.ok){var er=await res.text();throw new Error(er||"API error "+res.status)}if(!res.body||!res.body.getReader)throw new Error("Streaming is unavailable on this WebKit build.");wait.row.remove();var live=bubble("assistant","",null,false);var reader=res.body.getReader(),decoder=new TextDecoder("utf-8"),buf="",answer="",finalData=null;while(true){var rr=await reader.read();if(rr.done)break;buf+=decoder.decode(rr.value,{stream:true});var lines=buf.split("\n");buf=lines.pop();for(var li=0;li<lines.length;li++){var line=lines[li].trim();if(line.indexOf("data: ")!==0)continue;var raw=line.slice(6);if(raw==="[DONE]")continue;try{var ev=JSON.parse(raw);if(ev.type==="response.output_text.delta"&&ev.delta){answer+=ev.delta;live.text.innerHTML=md(answer);bottom()}if(ev.type==="response.completed"&&ev.response){finalData=ev.response}}catch(_){} }}if(!answer)answer="No text was returned.";c.messages.push({role:"assistant",text:answer});c.updated=Date.now();lastUsage=finalData&&finalData.usage?finalData.usage:null;saveChats();render();renderUsage()}catch(e){wait.row.remove();if(e.name!=="AbortError"){c.messages.push({role:"assistant",text:"Error: "+(e.message||String(e))});saveChats();render()}}finally{running=false;aborter=null;sendState();renderChats()}}
function stop(){if(aborter)aborter.abort();running=false;sendState()}function regenerate(){var c=current();if(!c||!c.messages.length)return;while(c.messages.length&&c.messages[c.messages.length-1].role==="assistant")c.messages.pop();var u=c.messages.pop();if(!u)return;P.value=u.text||"";pendingImage=u.image||null;renderAttachment();saveChats();render();resize();sendMessage()}
function copyText(t){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(t).catch(function(){fallback(t)});else fallback(t)}function fallback(t){var x=document.createElement("textarea");x.value=t;document.body.appendChild(x);x.select();document.execCommand("copy");x.remove()}$("copyBtn").onclick=function(){copyText(menuText);hide(menuO)};$("regenBtn").onclick=function(){hide(menuO);regenerate()};$("shareBtn").onclick=function(){hide(menuO);if(window.webkit&&window.webkit.messageHandlers.share)window.webkit.messageHandlers.share.postMessage(menuText);else copyText(menuText)};$("menuCancel").onclick=function(){hide(menuO)};menuO.onclick=function(e){if(e.target===menuO)hide(menuO)};msgMenu.onclick=function(e){e.stopPropagation()};
function renderUsage(){if(!showUsage||!lastUsage){usageLine.textContent="AI can make mistakes.";return}usageLine.textContent=(lastUsage.input_tokens||0)+" input • "+(lastUsage.output_tokens||0)+" output tokens"}
document.addEventListener("click",function(e){var a=e.target.closest&&e.target.closest("a");if(a){e.preventDefault();if(window.webkit&&window.webkit.messageHandlers.openURL)window.webkit.messageHandlers.openURL.postMessage(a.href)}});document.addEventListener("gesturestart",function(e){e.preventDefault()});if(window.visualViewport)window.visualViewport.addEventListener("resize",function(){document.body.classList.toggle("keyboard",normalH-window.visualViewport.height>120);bottom()});
resize();sendState();render();renderChats();renderUsage();window.ChatGPT15={version:"2.0",ready:true};})();